version: '3'
# for setting up jenkins server
services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom
    container_name: proxy
    restart: always
    ports:
      - '80:80'
    environment:
      - NGINX_SERVER_NAME=server_node
    network_mode: "host"

  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins-server
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    network_mode: "host"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-log:/var/log/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-data:
  jenkins-log:
